package db

import "context"

// Querier interface will be generated by sqlc
// Run: sqlc generate
type Querier interface{}

type Queries struct{}

func New(db DBTX) *Queries {
	return &Queries{}
}

type DBTX interface {
	Exec(context.Context, string, ...interface{}) (interface{}, error)
	Query(context.Context, string, ...interface{}) (interface{}, error)
	QueryRow(context.Context, string, ...interface{}) interface{}
}
